### ISSUE TITLE
"Additional Information" should be part of the introduction

### ISSUE THREAD

**Issue by paulehoffman** [kjd/draft-davies-internal-tld#3]
It is uncommon to have a section after the IANA considerations and security considerations. Instead, this section could be a subsection of the introduction.

**Comment by kjd** [comment]
My take is what is in "Additional Information" is just more for academic curiosity as to how we got here, and is not really relevant on how to use .internal. I'd like it to be further down just not to distract from the core issue of (a) why this exists, and (b) how to use it. 

FWIW, took the exact same approach in RFC 9121 and it seemed to survive the editorial process. The administrivia of how we got to the RFC is in an Additional Information section at the end.

**Comment by paulehoffman** [comment]
Interesting about RFC 9121. The RPC do not stick as close to their rules as we might expect.
